echo >{global.ercf_selector_file} "; AUTOGENERATED FILE DO NOT EDIT"
echo >>{global.ercf_selector_file} "set global.ercf_selector_pos = " ^ global.ercf_selector_pos
echo >>{global.ercf_selector_file} "set global.ercf_extruder_loaded = " ^ global.ercf_extruder_loaded
